name: Build and Release Binaries

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Build binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # see https://docs.github.com/en/actions/reference/runners/github-hosted-runners
          - os: ubuntu-latest
            suffix: linux-x86_64
          - os: macos-14
            suffix: macos-arm64

    steps:
      - uses: actions/checkout@v5

      - name: Determine version
        id: version
        run: |
          if [ -n "${{ github.ref_name }}" ]; then
            echo "version=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Build
        run: |
          mkdir -p build
          VERSION="${{ steps.version.outputs.version }}"
          echo "fake binary" > build/myapp-${VERSION}-${{ matrix.suffix }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-${{ matrix.suffix }}
          path: build/myapp-${{ steps.version.outputs.version }}-${{ matrix.suffix }}

  release:
    name: Upload artifacts to release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Download all build artifacts produced in the previous job
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      # Upload artifacts to GitHub Release
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
