name: 'Build and Release Binaries'

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-release:
    uses: test-org-for-release/.github/.github/workflows/build-release.yaml@main
    with:
      app-name: test-app
